import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class TwoSevenCountTest
{
    @Test
    void testTwoSevenReturnsExpected()
    {
        final String two = "Two";
        final String seven = "Seven";
        String expected = new StringBuilder().append( "1\n" )
                                             .append( two + "\n" )
                                             .append( "3\n" )
                                             .append( two + "\n" )
                                             .append( "5\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "9\n" )
                                             .append( two + "\n" )
                                             .append( "11\n" )
                                             .append( two + "\n" )
                                             .append( "13\n" )
                                             .append( two + seven + "\n" )
                                             .append( "15\n" )
                                             .append( two + "\n" )
                                             .append( "17\n" )
                                             .append( two + "\n" )
                                             .append( "19\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "23\n" )
                                             .append( two + "\n" )
                                             .append( "25\n" )
                                             .append( two + "\n" )
                                             .append( "27\n" )
                                             .append( two + seven + "\n" )
                                             .append( "29\n" )
                                             .append( two + "\n" )
                                             .append( "31\n" )
                                             .append( two + "\n" )
                                             .append( "33\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "37\n" )
                                             .append( two + "\n" )
                                             .append( "39\n" )
                                             .append( two + "\n" )
                                             .append( "41\n" )
                                             .append( two + seven + "\n" )
                                             .append( "43\n" )
                                             .append( two + "\n" )
                                             .append( "45\n" )
                                             .append( two + "\n" )
                                             .append( "47\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "51\n" )
                                             .append( two + "\n" )
                                             .append( "53\n" )
                                             .append( two + "\n" )
                                             .append( "55\n" )
                                             .append( two + seven + "\n" )
                                             .append( "57\n" )
                                             .append( two + "\n" )
                                             .append( "59\n" )
                                             .append( two + "\n" )
                                             .append( "61\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "65\n" )
                                             .append( two + "\n" )
                                             .append( "67\n" )
                                             .append( two + "\n" )
                                             .append( "69\n" )
                                             .append( two + seven + "\n" )
                                             .append( "71\n" )
                                             .append( two + "\n" )
                                             .append( "73\n" )
                                             .append( two + "\n" )
                                             .append( "75\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "79\n" )
                                             .append( two + "\n" )
                                             .append( "81\n" )
                                             .append( two + "\n" )
                                             .append( "83\n" )
                                             .append( two + seven + "\n" )
                                             .append( "85\n" )
                                             .append( two + "\n" )
                                             .append( "87\n" )
                                             .append( two + "\n" )
                                             .append( "89\n" )
                                             .append( two + "\n" )
                                             .append( seven + "\n" )
                                             .append( two + "\n" )
                                             .append( "93\n" )
                                             .append( two + "\n" )
                                             .append( "95\n" )
                                             .append( two + "\n" )
                                             .append( "97\n" )
                                             .append( two + seven + "\n" )
                                             .append( "99\n" )
                                             .append( two )
                                             .toString();

        String twoSevenString = new TwoSevenCount().countAndGet();

        Assertions.assertEquals( expected, twoSevenString );
    }
}
